parameters:
#    persistenciapersistencia.example.class: Persistencia\persistenciaBundle\Example

services:
#    persistenciapersistencia.example:
#        class: %persistenciapersistencia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
